version: '3'
services:
  user:
    image: ubuntu
    container_name: user_daemon
    command: sleep infinity
    links:
      - db
  db:
     image: mysql
     container_name: scanner_db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  