version: '3'
services:
  workstation:
    image: ubuntu
    container_name: user_daemon
    volumes:
    - ./:/src
    command: sleep infinity
  db:
     image: mysql
     container_name: scanner_db
     command: mysql sql/schema.sql
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  